---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
script:
  - rm -rf node_modules && yarn install --frozen-lockfile
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      if: branch = develop
      node_js: lts/*
      script:
        - rm -rf node_modules && yarn install --frozen-lockfile
        - npm install --global expo-cli
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive